export const ADD_ITEM           = 'CART/ADD_ITEM'
export const REMOVE_ITEM        = 'CART/REMOVE_ITEM'
export const CLEAR_ITEMS        = 'CART/CLEAR_ITEMS'
export const QUANTITY_INCREMENT = 'CART/QUANTITY_INCREMENT'
export const QUANTITY_DECREMENT = 'CART/QUANTITY_DECREMENT'

export const SET_USER = 'AUTH/SET_USER'